apiVersion: v1
kind: Service
metadata:
  name: pvc-svc
spec:
  selector:
    app: pvc-app
  type: NodePort
  ports:
  - port: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
  labels:
    name: pvc-pod
spec:
  volumes:
  - name: pvc-volume
    persistentVolumeClaim:
      claimName: pvc
  containers:
  - name: pvc-app
    image: nginx
    ports:
    - containerPort: 80
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: pvc-volume

---
# # Stage 1. Create PVC

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: PVC_NAME
# spec:
#   storageClassName: ""
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Mi

# # ---
# # # Stage 2 Create a volume for the PVC
# # apiVersion: v1
# # kind: PersistentVolume
# # metadata:
# #   name: PV_NAME
# # spec:
# #   storageClassName: ""
# #   capacity:
# #     storage: 100Mi
# #   accessModes:
# #   STORAGE_MODE
# #   # ReadWriteMany
# #   # ReadWriteMany
# #   # ReadOnlyMany
# #   # Once mounted by one of the options is not accessible
# #   # anymore. So having 2 options specified means that
# #   # only one access mode will be used and once used
# #   # it will not be available for mount.
# #   hostPath:
# #     path: "HOST_PATH_TO_DIRECTORY"