apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloapp-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloapp
  template:
    metadata:
      name: helloapp
      labels:
        app: helloapp
    spec:
      containers:
      - name: helloapp
        image: nginx
        resources: {}
        ports:
        - containerPort: 80
          name: http
          protocol: TCP