
apiVersion: v1
kind: Pod
metadata:
  name: tools
  labels:
    app: tools
spec:
  containers:
  - name: tools
    image: giantswarm/tiny-tools
    resources: {}
    command: ["/bin/sh"]
    args: ["-c", "sleep 3600"]

---
kind: Service
apiVersion: v1
metadata:
  name: external-web
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
---
kind: Endpoints
apiVersion: v1
metadata:
  name: external-web
subsets: 
  - addresses:
    - ip: 1.1.1.1
    ports:
      - port: 80 
        name: http