apiVersion: v1
kind: Pod
metadata:
  name: init-containers
  labels:
    name: init-containers
spec:
  restartPolicy: Never
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    startupProbe:
      httpGet:
        path: /
        port: 80
    livenessProbe:
      httpGet:
        path: /
        port: 80
    readinessProbe:
      httpGet:
        path: /
        port: 80
  initContainers:
  - name: main
    image: busybox
    command: ['sh', '-c', 'sleep 30;']