apiVersion: v1
kind: Pod
metadata:
  name: probes-readiness
  labels:
    name: probes-readiness
spec:
  restartPolicy: Never
  containers:
  - name: main
    image: busybox
    command: ['sh', '-c', 'while true; do sleep 5; done;']    
    livenessProbe:
      exec:
        command: ['sh', '-c', 'echo $(date +%s): LIVENESS >> /tmp/timing.txt']
    readinessProbe:
      exec:
        command: ['sh', '-c', 'echo $(date +%s): READINESS >> /tmp/timing.txt; exit 1']