apiVersion: v1
kind: Pod
metadata:
  name: probes-readiness-startupprobe
  labels:
    name: probes-readiness-startupprobe
spec:
  restartPolicy: Never
  containers:
  - name: main
    image: busybox
    command: ['sh', '-c', 'while true; do sleep 5; done;']
    startupProbe:
      exec:
        command: ['sh', '-c', 'echo $(date +%s): LIVENESS >> /tmp/timing.txt; exit 1']
      failureThreshold: 7
      periodSeconds: 10
    livenessProbe:
      exec:
        command: ['sh', '-c', 'echo $(date +%s): LIVENESS >> /tmp/timing.txt; exit 1']
      failureThreshold: 7
      periodSeconds: 10
    readinessProbe:
      exec:
        command: ['sh', '-c', 'echo $(date +%s): READINESS >> /tmp/timing.txt;']

---

apiVersion: v1
kind: Pod
metadata:
  name: probes-readiness-threshold
  labels:
    name: probes-readiness-threshold
spec:
  restartPolicy: Never
  containers:
  - name: main
    image: busybox
    command: ['sh', '-c', 'while true; do sleep 5; done;']
    livenessProbe:
      exec:
        command: ['sh', '-c', 'echo $(date +%s): LIVENESS >> /tmp/timing.txt; exit 1']
      failureThreshold: 7
      periodSeconds: 10
    readinessProbe:
      exec:
        command: ['sh', '-c', 'echo $(date +%s): READINESS >> /tmp/timing.txt;']
