
apiVersion: v1
kind: Pod
metadata:
  name: restartpolicy
  labels:
    name: restartpolicy
spec:
  restartPolicy: Always
  maxRetries: "10" #max number of retries
  containers:
  - name: main
    image: busybox
    # command: ['sh', '-c', 'echo $(date +%s): START >> /loap/timing.txt; sleep 30; echo $(date +%s): END >> /loap/timing.txt; exit 1;']
    command: ['sh', '-c', 'echo $(date +%T) START; sleep 5; echo $(date +%T) END;']