apiVersion: v1
kind: Secret
metadata:
  name: secret2
stringData:
  .notEncoded: |
    "File
    secret
    OK"
  anotherKey: |
    "Multi
    line
    values
    are
    supported"

---
apiVersion: v1
kind: Pod
metadata:
  name: tools
spec:
  containers:
    - name: tools
      image: giantswarm/tiny-tools
      command: ["sleep", "3600"]
      resources: {}
      env:
      - name: INSIDE_CONTIANER_ENVIRONMENT_NAME
        valueFrom:
          secretKeyRef:
            name: NAME_OF_THE_SECRET
            key: NAME_OF_THE_KEY
      volumeMounts:
      - name: NAME_OF_THE_VOLUME
        mountPath: "/PATH_TO_DIR_WHERE_TO_MOUNT"
        readOnly: true
  volumes:
    - name: NAME_OF_THE_VOLUME
      secret:
        secretName: NAME_OF_THE_SECRET